-   id: pylint-py3k
    name: Python 3 porting mode check
    description: This hook use pylint --py3k option to check Python 3 porting.
    entry: ./py3k.py
    language: script
    files: \.py$
-   id: pylint-score-limit
    name: Pylint Score Limit
    description: This hook runs pylint and checks it's score
    entry: ./score_limit.py
    language: script
    files: \.py$
